package presentacio.userAdministration.vistaFilaUsuari;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import domini.usuari.CtrlUsuari;
import domini.usuari.UserException;
import domini.usuari.Usuari;
import presentacio.CtrlPresentacio;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class FilaUsuari {
    private JPanel panel;
    private JButton editarButton;
    private JLabel usernameField;
    private JLabel typeField;

    public FilaUsuari(Usuari usuari) {
        usernameField.setText(usuari.getUsername());
        if (Objects.equals(usuari.getTipus(), CtrlUsuari.TYPE_ADMIN)) {
            typeField.setText("Administrador");
        } else {
            typeField.setText("Client");
        }
        editarButton.addActionListener(e -> {
            try {
                CtrlPresentacio.getInstance().getCtrlDomini().ctrlUsuari.eliminarUsuari(usuari.getUsername());
                CtrlPresentacio.getInstance().reloadUserList();
            } catch (UserException ex) {
                CtrlPresentacio.getInstance().displayError(ex.getMessage(), null);
            }
        });
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(3, 5, new Insets(0, 0, 0, 0), -1, -1));
        usernameField = new JLabel();
        usernameField.setText("Nom d'usuari");
        panel.add(usernameField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        separator1.setBackground(new Color(-983553));
        separator1.setForeground(new Color(-1));
        panel.add(separator1, new GridConstraints(2, 0, 1, 5, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 5), new Dimension(-1, 5), 0, false));
        editarButton = new JButton();
        editarButton.setText("Eliminar usuari");
        panel.add(editarButton, new GridConstraints(1, 1, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        typeField = new JLabel();
        typeField.setText("Tipus");
        panel.add(typeField, new GridConstraints(0, 1, 1, 4, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
