package presentacio.recomanacionsAdministration;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import domini.recomanacio.RecomanacionsException;
import presentacio.CtrlPresentacio;

import javax.swing.*;
import java.awt.*;
import java.text.ParseException;
import java.util.List;

public class VistaManagementRecomanacions {
    private JTextField idUsuari;
    private JButton avaluarRecomanacionsButton;
    private JPanel jPanel;
    private JLabel avaluacio;

    public VistaManagementRecomanacions() {
        avaluarRecomanacionsButton.addActionListener(e -> {
            Integer userID = Integer.parseInt(idUsuari.getText());
            Double valor = 0.0;
            try {
                CtrlPresentacio.getInstance().getCtrlDomini().llegirTest();
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            try {
                valor = CtrlPresentacio.getInstance().getCtrlDomini().ctrlRecomanacio.avaluarQualitat(userID);
            } catch (RecomanacionsException ex) {
                CtrlPresentacio.getInstance().displayError(ex.getMessage(), null);
            }

            avaluacio.setText("DCG: " + valor.toString());
        });
    }

    public JPanel getPanel() {
        return jPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Introdueix el identificador de l'usuari:");
        jPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        jPanel.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        idUsuari = new JTextField();
        idUsuari.setText("");
        jPanel.add(idUsuari, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer2 = new Spacer();
        jPanel.add(spacer2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        avaluarRecomanacionsButton = new JButton();
        avaluarRecomanacionsButton.setText("Avaluar Últimes Recomanacions");
        jPanel.add(avaluarRecomanacionsButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        avaluacio = new JLabel();
        avaluacio.setText("DCG: ");
        jPanel.add(avaluacio, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
