package presentacio.iniciarSessio;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import domini.usuari.CtrlUsuari;
import domini.usuari.UserException;
import presentacio.CtrlPresentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 * Classe que genera la vista per iniciar la sessió d'usuari
 *
 * @author Hector Godoy Creus
 */
public class VistaIniciarSessio {
    private JPanel panel;
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JButton iniciarSessioButton;
    private JButton crearUsuariButton;

    public VistaIniciarSessio() {
        iniciarSessioButton.addActionListener(e -> {
            if (CtrlPresentacio.getInstance().getCtrlDomini().ctrlValoracio.getValoracioMaxima() == -1.0) {
                CtrlPresentacio.getInstance().displayEstablirMaxValoracio();
            }
            else {
                String username = usernameField.getText();
                String pass = new String(passwordField.getPassword());
                try {
                    CtrlPresentacio.getInstance().getCtrlDomini().ctrlUsuari.iniciarSessio(username, pass);

                    //Mostrem la vista adequada segons el tipus d'usuari
                    if (CtrlPresentacio.getInstance().getCtrlDomini().ctrlUsuari.getUsuariIniciat().getTipus().equals(CtrlUsuari.TYPE_ADMIN)) {
                        CtrlPresentacio.getInstance().mostrarVistaAdmin();
                    } else {
                        CtrlPresentacio.getInstance().mostrarVistaUsuari();
                    }
                } catch (UserException ex) {
                    CtrlPresentacio.getInstance().displayError(ex.getMessage(), null);
                }
            }
        });

        crearUsuariButton.addActionListener(e -> CtrlPresentacio.getInstance().switchPanel("vistaRegistrarUsuari"));
    }

    public static JMenuBar getMenuBar() {
        JMenuBar menuBar;
        JMenu menu;
        JMenuItem menuItem;

        //Create the menu bar.
        menuBar = new JMenuBar();

        //Build the File Menu.
        menu = new JMenu("Fitxer");
        menu.setMnemonic(KeyEvent.VK_F);
        menuBar.add(menu);

        menuItem = new JMenuItem("Carregar dades de fitxer...");
        menuItem.addActionListener(e -> CtrlPresentacio.getInstance().displayCarregarFitxers());
        menu.add(menuItem);

        menuItem = new JMenuItem("Desar estat del sistema...");
        menuItem.addActionListener(e -> CtrlPresentacio.getInstance().getCtrlDomini().desarEstat());
        menu.add(menuItem);

        //Add exit button
        menu.addSeparator();
        menuItem = new JMenuItem("Sortir");
        menuItem.addActionListener(e -> System.exit(0));
        menu.add(menuItem);


        return menuBar;
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(9, 3, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel.add(spacer3, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panel.add(spacer4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        usernameField = new JTextField();
        usernameField.setToolTipText("username");
        panel.add(usernameField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordField = new JPasswordField();
        passwordField.setText("");
        passwordField.setToolTipText("password");
        panel.add(passwordField, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Usuari");
        panel.add(label1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Contrasenya");
        panel.add(label2, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        iniciarSessioButton = new JButton();
        iniciarSessioButton.setText("Iniciar sessió");
        panel.add(iniciarSessioButton, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        crearUsuariButton = new JButton();
        crearUsuariButton.setText("Crear usuari");
        panel.add(crearUsuariButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
