package presentacio.vistaUnItem;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import domini.item.Item;

import javax.swing.*;
import java.awt.*;

public class vistaUnItem {
    private JLabel nomItem;
    private JTextPane descItem;
    private JPanel itemPanel;
    private JScrollPane scrollPane;

    public vistaUnItem(Item item, String nom) {
        nomItem.setText(nom);
        String[] llistaAtributs = item.toString().split("\\|");
        String atributs = "";
        for (String atrib : llistaAtributs) {
            if (atrib.contains("ItemID ")) atributs = atrib;
            else if (atrib.contains("Atributs ")) atributs = atributs + "\n" + "\n" + atrib;
            else if (!atrib.isEmpty()) atributs = atributs + "\n" + atrib;
        }
        descItem.setText(atributs);
        descItem.setCaretPosition(0);
        descItem.setEditable(false);

        scrollPane.setViewportView(descItem);
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);
    }

    public JPanel getItemPanel() {
        return itemPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        itemPanel = new JPanel();
        itemPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        nomItem = new JLabel();
        nomItem.setText("Nom item");
        itemPanel.add(nomItem, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        itemPanel.add(scrollPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        descItem = new JTextPane();
        descItem.setText("");
        scrollPane.setViewportView(descItem);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return itemPanel;
    }

}
