package presentacio.vistaPrincipal;

import domini.usuari.UserException;
import presentacio.CtrlPresentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;


/**
 * Classe que genera la vista principal de la sessió d'un administrador
 *
 * @author Hector Godoy Creus
 */
public class VistaPrincipalAdmin {

    private JPanel panel1;

    public JPanel getPanel1() {
        return panel1;
    }

    //El menu ens permetrà accedir a l'administració del sistema
    public static JMenuBar getMenuBar() {
        JMenuBar menuBar;
        JMenu menu;
        JMenuItem menuItem;

        //Create the menu bar.
        menuBar = new JMenuBar();

        //Build the File Menu.
        menu = new JMenu("Fitxer");
        menu.setMnemonic(KeyEvent.VK_F);
        menuBar.add(menu);

        menuItem = new JMenuItem("Carregar dades de fitxer...");
        menuItem.addActionListener(e -> CtrlPresentacio.getInstance().displayCarregarFitxers());
        menu.add(menuItem);

        menuItem = new JMenuItem("Desar estat del sistema...");
        menuItem.addActionListener(e -> CtrlPresentacio.getInstance().getCtrlDomini().desarEstat());
        menu.add(menuItem);

        menu.addSeparator();

        menuItem = new JMenuItem("Sortir");
        menuItem.addActionListener(e -> System.exit(0));
        menu.add(menuItem);

        // Afegir menu admin
        menu = new JMenu("Administrar");
        menu.setMnemonic(KeyEvent.VK_A);
        menuBar.add(menu);

        menuItem = new JMenuItem("Items");
        menuItem.addActionListener(e -> CtrlPresentacio.getInstance().switchPanel("vistaManagementItems"));
        menu.add(menuItem);

        menuItem = new JMenuItem("Usuaris");
        menuItem.addActionListener(e -> CtrlPresentacio.getInstance().switchPanel("vistaManagementUsuaris"));
        menu.add(menuItem);

        menuItem = new JMenuItem("Recomanacions");
        menuItem.addActionListener(e -> CtrlPresentacio.getInstance().switchPanel("vistaManagementRecomanacions"));
        menu.add(menuItem);

        // Afegir menu admin
        menu = new JMenu("Sessio");
        menu.setMnemonic(KeyEvent.VK_A);
        menuBar.add(menu);

        menuItem = new JMenuItem("Tancar sessio");
        menuItem.addActionListener(e -> {
            try {
                CtrlPresentacio.getInstance().getCtrlDomini().ctrlUsuari.tancarSessio();
                CtrlPresentacio.getInstance().mostrarVistaIniciarSessio();
            } catch (UserException ex) {
                CtrlPresentacio.getInstance().displayError(ex.getMessage(), null);
            }
        });
        menu.add(menuItem);

        return menuBar;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Benvingut");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Utilitza les opcions del menu per administrar el sistema");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        panel1.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
